<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>TATAPP</AssemblyName>
    <RootNamespace>TATAPP.App</RootNamespace>
    <VersionPrefix>0.3.1</VersionPrefix>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\TATAPP.Core\TATAPP.Core.csproj" />
  </ItemGroup>
</Project>
